### ISSUE TITLE
KeyError: 'resnet18'

### ISSUE THREAD

**Issue by c1a1o1** [d-li14/face-attribute-prediction#4]
E:\Users\Raytine\Anaconda3\python.exe F:/imageedit/face-attribute-prediction-master/main.py
=> creating model 'resnet18'
Traceback (most recent call last):
  File "F:/imageedit/face-attribute-prediction-master/main.py", line 417, in <module>
    main()
  File "F:/imageedit/face-attribute-prediction-master/main.py", line 135, in main
    model = models.__dict__[args.arch]()
KeyError: 'resnet18'

**Comment by xugangtongji** [comment]
there is just res50 had been wrritten in model. Chang main res18 to res50
